print('Working with Strings.')
print()
c = 'Carro forte'
a = input('What\'s your name? ').capitalize()
b = input('What\'s your last name? ')
print(c)
print(a+' '+b)
print('Rob\nTorres')
print(a.upper())
print(b.capitalize())
print(a.lower())
print(a.islower())
print(len(a))
print(a[1:2])
print(b[-1])
print(b.index('o'))
print(c.replace('forte', 'Strong'))
